name: Node.js Package
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"
      - run: yarn
      # Publish to npm
      - run: yarn publish observatory --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v1
        with:
          registry-url: "https://npm.pkg.github.com"
      # Publish to GitHub Packages
      - run: yarn publish observatory
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
